language: node_js
node_js:
  - '0.10'
before_script:
  - "npm --version"
notifications:
  email: false
deploy:
  edge: true
  provider: cloudfoundry
  username: cuong.chung@harveynash.vn
  password: 8970627cuong
  api: https://api.run.pivotal.io
  organization: Pivotal_demo
  space: development
  on:
    repo: contactquanghien/pivotaldemo
    branch: master
    #   tags: true
    #   all_branches: true