language: node_js
node_js:
  - '0.10'
before_script:
  - "npm --version"
notifications:
  email: false
deploy:
 edge: true
 skip_cleanup: true
 provider: cloudfoundry
 api: https://api.run.pivotal.io
 username:
   secure: cuong.chung@harveynash.vn
 password:
   secure: 8970627cuong
 organization: Pivotal_demo
 space: development
 on:
   repo: contactquanghien/pivotaldemo
   branch: master
   tags: true